# Project Generate Parallel Database

In this section we're going to play around with Differential Privacy in the context of a database query. The database is going to be a VERY simple database with only one boolean column. Each row corresponds to a person. Each value corresponds to whether or not that person has a certain private attribute (such as whether they have a certain disease, or whether they are above/below a certain age). We are then going to learn how to know whether a database query over such a small database is differentially private or not - and more importantly - what techniques are at our disposal to ensure various levels of privacy

### First We Create a Simple Database
Step one is to create our database 
   - we're going to do this by initializing a random list of 1s and 0s (which are the entries in our database). 
   
**Note** - the number of entries directly corresponds to the number of people in our databas

In [1]:
# Database

import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5

db


tensor([1, 0, 0,  ..., 1, 0, 0], dtype=torch.uint8)

In [2]:
db.shape

torch.Size([5000])

In [3]:
db[0:5]


tensor([1, 0, 0, 0, 1], dtype=torch.uint8)

In [4]:
#For Removing entry 2 
remove_index = 2 

In [6]:
# to Remove in Pytroch - slice before and after the ones you want to remove
# step 1 : before
db[0:2]

# step 2 : After
db[3:]

# Step3 : Concatenate and diaply ony the first 5
torch.cat((db[0:2],db[3:]))[0:5]

tensor([1, 0, 0, 1, 1], dtype=torch.uint8)

In [15]:
# Create a function - To Remove Index
def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index],db[remove_index+1:]))

In [8]:
# remove first entry
get_parallel_db(db,0)[0:5]

tensor([0, 0, 0, 1, 1], dtype=torch.uint8)

In [16]:
# remove first entry and shows the size
get_parallel_db(db,1).shape

torch.Size([4999])

In [17]:
# Remove no that does not exist 
# it will return the entire database size
get_parallel_db(db,5423).shape

torch.Size([5000])

In [18]:
# Create Function 2 to iterate through db and create parallel db

def get_parallel_dbs(db):
    parallel_dbs = list()
    for i in range(len(db)):
        pdb = get_parallel_db(db,i)
        parallel_dbs.append(pdb)
    return parallel_dbs

In [19]:
pdbs = get_parallel_dbs(db)

In [ ]:
pdbs


In [21]:
# Function 3 to 
def create_db_and_parallels(num_entries):
    db = torch.rand(num_entries) > 0.5
    pdb = get_parallel_dbs(db)
    
    return db, pdbs

In [22]:
db , pdbs = create_db_and_parallels(20)

In [23]:
db


tensor([1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0],
       dtype=torch.uint8)