In [ ]:
import torch

In [18]:
def activation(x):
    return 1/(1+torch.exp(-x))


In [9]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [17]:
## Exercise: Calculate the output of the network with input features features, weights weights, and bias bias. Similar to Numpy, PyTorch has a torch.sum() function, as well as a  .sum() method on tensors, for taking sums. Use the function  activation defined above as the activation function.
## and bias tensors
## Solution for exercise 1
h = torch.sum(features * weights) + bias
print(h)
y = activation(h)
print (y)

RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1

In [ ]:
Exercise 2: Calculate the output of our little network using matrix multiplication

In [16]:
## Matrix multiplication using torch.mm()  or torch.matmul()
# use tensor.shape to reshape the matix for multiplication
weights.view(5, 1)


tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [18]:
torch.mm(features, weights.view(5, 1))


tensor([[-1.9796]])

In [16]:
## Exercise: Calculate the output of our little network using matrix multiplication.
h = torch.mm(features , weights.view(5, 1)) + bias
print(h)
y = activation(h)
print (y)

RuntimeError: size mismatch, m1: [1 x 3], m2: [5 x 1] at ..\aten\src\TH/generic/THTensorMath.cpp:961

In [ ]:
Exercise: Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.

In [14]:
import torch

def activation(x):
    return 1/(1+torch.exp(-x))

### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [15]:
### Exercise 3 : Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.
## solution
h = activation(torch.mm(features,W1)+ B1)
y =activation(torch.mm(h,W2)+ B2)
print(h)
print(y)

tensor([[0.6813, 0.4355]])
tensor([[0.3171]])
