In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))


In [4]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [11]:
## Exercise: Calculate the output of the network with input features features, weights weights, and bias bias. Similar to Numpy, PyTorch has a torch.sum() function, as well as a  .sum() method on tensors, for taking sums. Use the function  activation defined above as the activation function.
## and bias tensors
## Solution for exercise 1
h = torch.sum(features * weights) + bias
print(h)
y = activation(h)
print (y)

tensor([[-1.6619]])
tensor([[0.1595]])


In [21]:
## Calculate the output of this network using the weights and bias tensors
torch.mm(features, weights)


RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at ..\aten\src\TH/generic/THTensorMath.cpp:961

In [16]:
## Matrix multiplication using torch.mm()  or torch.matmul()
# use tensor.shape to reshape the matix for multiplication
weights.view(5, 1)


tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [18]:
torch.mm(features, weights.view(5, 1))


tensor([[-1.9796]])

In [20]:
## Exercise: Calculate the output of our little network using matrix multiplication.
h = torch.mm(features , weights.view(5, 1)) + bias
print(h)
y = activation(h)
print (y)

tensor([[-1.6619]])
tensor([[0.1595]])
